export {default as elementUI} from "./element-ui"
export {default as elementPlus2} from "./element-plus2.0"
export {default as elementPlus} from "./element-plus"
export {default as fontAwesome470} from "./font-awesome.v4.7.0"
export {default as fontAwesome5XX} from "./fontawesome-5.x.x"
export {default as fontAwesome5XXPro} from "./fontawesome-5.x.x-pro"
export {default as fontAwesome6XX} from "./fontawesome-6.x.x"
export {default as antDesign} from "./antDesign"
export {default as tdesignIcons} from "./tdesignIcons"
export {default as arcoVueIcon} from "./arcoVueIcon"
export {default as layuiVue} from './layui-vue'
export {default as iconify} from './iconify'
